### ISSUE TITLE
Wrong documentation?

### ISSUE THREAD

**Issue by eddietejeda** [apohllo/CKAN#6] opened 2014-09-02 23:24 UTC
The documentation says that in order to change CKAN API endpoint you:

`CKAN::API.api_base = 'your API here'`

But that does not work.

`2.1.2 :007 > CKAN::API.api_base`
`NameError: uninitialized constant CKAN::API`

**Comment by apohllo** [comment] 2014-09-06 18:22
Hmm, I assume you have required the `ckan` lib, have you? The API module is defined in the main `ckan.rb` file, so this seems strange. Which Ruby version you use - I'll try to reproduce.

**Comment by eddietejeda** [comment] 2014-09-07 18:16
Yup. Calls to API work just fine. Only changing the api path appears to be broken.  

I am using Ruby 2.1.2  

## 

Eddie A Tejeda

**Comment by apohllo** [comment] 2014-09-09 16:05
Oh, I know the reason - the version that is on github was never released as a gem. So the documentation is newer than the gem in rubygems. If you are using bundler, you can provide the link to this repo. I will release a new gem soon.

**Closed as completed** 2022-11-16 18:19 UTC
